name: publish

on:
  release:
    types: [published, edited]
  workflow_dispatch:

jobs:
  publish:
    name: py${{ matrix.python-version }}-${{ matrix.platform.python-architecture }} os-${{ matrix.platform.os}}
    runs-on: ${{ matrix.platform.os }}
    strategy:
      matrix:
        python-version: [3.9]
        platform: [
          { os: "macOS-latest",   python-architecture: "x64"}
        ]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2 
        with:
          python-version: ${{ matrix.python-version }}
          architecture: ${{ matrix.platform.python-architecture }}
      
      - name: Install Cython
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install twine
      
      - name: Install dependencies 
        run: python setup.py install

      - name: Build .whl file
        run: python setup.py sdist bdist_wheel

      - name: Publish with twine
        run: |
        python -m twine upload --repository-url https://upload.pypi.org/legacy/ dist/* --username ${{secrets.PYPI_USERNAME}}  --password ${{secrets.PYPI_PASSWORD}}
        python -m twine uplaod --repository-url https://test.pypi.org/legacy/ dist/* --username ${{secrets.PYPI_USERNAME}}  --password ${{secrets.PYPI_PASSWORD}}
    
