name: test

on:
  push:
    branches: 
      - "*"
  pull_request:
  workflow_dispatch:

jobs:
  tests:
    name: py${{ matrix.python-version }}-${{ matrix.platform.python-architecture}}
    runs-on: ${{ matrix.platform.os }}
    strategy:
      matrix:
        python-version: [3.9]
        platform: [
          { os: "ubuntu-latest",  python-architecture: "x64"},
          { os: "macOS-latest",   python-architecture: "x64"},
          { os: "windows-latest", python-architecture: "x64"},
          { os: "windows-latest", python-architecture: "x86"},
        ]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2 
        with:
          python-version: ${{ matrix.python-version }}
          architecture: ${{ matrix.platform.python-architecture }}
      
      - name: Install Cython
      - run: |
          python -m pip install --upgrade pip
          pip install cython 
      
      - name: Install dependencies 
        run: python setup.py install

      - name: Test code with pytests
        run: python setup.py pytest
